# Generated by Django 5.0 on 2023-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fathers_name',
            field=models.TextField(default=None),
        ),
    ]
