# Generated by Django 5.0 on 2024-01-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraccount_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
