# Generated by Django 5.0 on 2023-12-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_ammount_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'deposit'), (2, 'withdraw'), (3, 'Loan'), (4, 'Loan paid'), (5, 'Money transfer')], null=True),
        ),
    ]
