# Generated by Django 5.0 on 2023-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('phone_no', models.CharField(max_length=12, verbose_name='Phone Number')),
            ],
        ),
    ]
